### ISSUE TITLE
Undo / Redo - Question (no error) 

### ISSUE THREAD

**Issue by thomasSailing** [moqod/ios-scratch-n-see#6]
Question 1: Question 1: I would like some help - how can I integrate an undo / redo? 
...
Question 2: With faster movement, the erased line has not soft curves
![img_0288](https://cloud.githubusercontent.com/assets/5857275/2851580/e14ce0a0-d11c-11e3-9060-b237979700fe.PNG)

**Comment by Jnis** [comment]
We updated library with your suggestion into question 2.
Regarding Question 1: i believe you can do next:
1/ add subclass from MDScratchImageView
2/ catch and save all TOUCHes for this view (touchesBegan and touchesMoved)
note: do not forget call super for each of this
3/ when you want UNDO, you need:
- remove part of saved TOUCHes
- update image ( self.image = self.image; )
- simulate touches ( [super touchesMoved:TOUCHes withEvent:nil]; )
